FROM golang:1.18-bullseye AS build

WORKDIR /app

COPY ./src/go.mod ./
COPY ./src/go.sum ./
RUN go mod tidy

COPY ./src ./

RUN go build -o /main


FROM debian:latest

WORKDIR /

COPY --from=build /main /main
RUN mkdir -p /logs/
RUN touch /logs/app.log
RUN chmod -R 777 /logs
COPY ./src/config.yml ./

EXPOSE 8080

# USER nonroot:nonroot

ENTRYPOINT ["/main"]
