FROM golang:1.18-bullseye AS build

WORKDIR /app

COPY ./src/go.mod ./
COPY ./src/go.sum ./
RUN go mod download

COPY ./src ./

RUN go build -o /main


FROM gcr.io/distroless/base-debian10

WORKDIR /

COPY --from=build /main /main

EXPOSE 8080

USER nonroot:nonroot

ENTRYPOINT ["/main"]